
POST http://localhost:8000/funql HTTP/1.1
content-type: application/json
token:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDAyNDQxODEuMDIzLCJ1c2Vyc0lkIjoiNjBkMWNkYTI3OGUzZjkwNTU4OTRlMDI3In0.t0JqV-lflf99RYgEEVy2m_MmW_k8XLSr6jQZpeUMmZbjmS4tZA4-GJYimF0z_8KUr_EoKQABzTaX6RV-3IrSDQ

{
    "details":{
        "set":{
            "orderId":"60d86f1e05564e2fa6a3e21a",
            "wareId":"60d6d3f7df52b722c3c57861"

        },
        "get":{

        }
    },
    "wants":{
        "model":"Order",
        "doit":"deleteWareOfOrder"
    }
}
