POST http://localhost:8000/funql HTTP/1.1
content-type: application/json

{
"contents":"dynamic",
    "details":{
        "set":{
            "_id":"616d2cf49a0fc0a7a43427be"
        },
        "get":{
"totalPrice":1,
        "orderStatus" :1
          }

        

    },
    "wants":{
        "model":"Order",
        "doit":"getOrder"
    }
}