POST http://localhost:8000/funql HTTP/1.1
content-type: application/json

{
    "contents":"dynamic",
    "details":{
        "set":{
         "userId":"614b5c87788d0544b5626d6a",
        #  "wareIds":["614b5c87788d0544b5626dd1"],
         "pagination":{
             "limit":10,
             "page":1
         }
        #  ,
        #  "orderStatus":"ACCEPTED",
        #  "paymentStatus":"PAID"
        },
        "get":{
            "wares":{
                "name":1
            },
            "orderStatus":1,
            "user":{
                "name":1
            }
        }
    },
    "wants":{
        "model":"Order",
        "doit":"getOrders"
    }
}